name: cypress_test

on: [push]

jobs:
  cypress-e2e-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run-Cypress-tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run start
          start: npm run test:e2e
          browser: chrome
