name: Hello World!

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: echo $(date) && ls ./
# jobs:
#   list_directory_job:
#     runs-on: ubuntu-20.04
#     steps:
#       - name: List directory
#         run: ls -l
# - name: print_date
#     run: echo "Hello World!"
