name: lint_code

on:
  push:
    branches:
      - master

Jobs:
  lint_my_code:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
      - name: install dependencies
        run: npm install
      - name: check linters
        run: npm run eslint
