name: test_my_app

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  run_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
      - name: install dependencies
        run: npm install
      - name: run test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:8080
